### ISSUE TITLE
Implementación de Tooltips

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/santander.biodiversidad.co#15]
![Captura de pantalla 2019-02-14 a la(s) 5.14.07 p. m..png](https://images.zenhubusercontent.com/5b0ed04054b51e4165e1d59d/ec720a30-48df-484d-aa4e-3f8f8d39617d)

Tooltip en las filas de Especies Migratorias, Exóticas y Endémicas

**Comment by dapino** [comment]
No necesariamente tooltip

**Comment by camiplata** [comment]
El disclaimer de exóticas ya no aplica.
Solo se necesita para endémicas y migratorias
